; Data from 12B6 to 12B8 (3 bytes)	
_screen_title_screen_load:	
	.db $CD $2B $08
	
; Data from 12B9 to 12BB (3 bytes)	
	.db $CD $A2 $0A
	
; Data from 12BC to 12BE (3 bytes)	
	.db $CD $51 $0B
	
; Data from 12BF to 12C1 (3 bytes)	
	.db $CD $E3 $0A
	
; Data from 12C2 to 12C4 (3 bytes)	
	.db $21 $0A $15
	
; Data from 12C5 to 12C5 (1 bytes)	
	.db $E5
	
; Data from 12C6 to 12C8 (3 bytes)	
	.db $21 $35 $13
	
; Data from 12C9 to 12C9 (1 bytes)	
	.db $E5
	
; Data from 12CA to 12CC (3 bytes)	
	.db $CD $E9 $0D
	
; Data from 12CD to 12CD (1 bytes)	
	.db $F1
	
; Data from 12CE to 12D0 (3 bytes)	
	.db $21 $06 $0C
	
; Data from 12D1 to 12D1 (1 bytes)	
	.db $E3
	
; Data from 12D2 to 12D4 (3 bytes)	
	.db $21 $41 $13
	
; Data from 12D5 to 12D5 (1 bytes)	
	.db $E5
	
; Data from 12D6 to 12D8 (3 bytes)	
	.db $CD $E9 $0D
	
; Data from 12D9 to 12D9 (1 bytes)	
	.db $F1
	
; Data from 12DA to 12DC (3 bytes)	
	.db $21 $14 $0C
	
; Data from 12DD to 12DD (1 bytes)	
	.db $E3
	
; Data from 12DE to 12E0 (3 bytes)	
	.db $21 $48 $13
	
; Data from 12E1 to 12E1 (1 bytes)	
	.db $E5
	
; Data from 12E2 to 12E4 (3 bytes)	
	.db $CD $E9 $0D
	
; Data from 12E5 to 12E5 (1 bytes)	
	.db $F1
	
; Data from 12E6 to 12E8 (3 bytes)	
	.db $21 $1C $17
	
; Data from 12E9 to 12E9 (1 bytes)	
	.db $E3
	
; Data from 12EA to 12EC (3 bytes)	
	.db $21 $4F $13
	
; Data from 12ED to 12ED (1 bytes)	
	.db $E5
	
; Data from 12EE to 12F0 (3 bytes)	
	.db $CD $E9 $0D
	
; Data from 12F1 to 12F1 (1 bytes)	
	.db $F1
	
; Data from 12F2 to 12F2 (1 bytes)	
	.db $F1
	
; Data from 12F3 to 12F5 (3 bytes)	
	.db $CD $25 $08
	
; Data from 12F6 to 12F8 (3 bytes)	
	.db $21 $32 $00
	
; Data from 12F9 to 12F9 (1 bytes)	
	.db $E5
	
; Data from 12FA to 12FC (3 bytes)	
	.db $CD $63 $11
	
; Data from 12FD to 12FF (3 bytes)	
	.db $21 $4B $00
	
; Data from 1300 to 1300 (1 bytes)	
	.db $E3
	
; Data from 1301 to 1303 (3 bytes)	
	.db $CD $9E $11
	
; Data from 1304 to 1304 (1 bytes)	
	.db $F1
	
; Data from 1305 to 1305 (1 bytes)	
	.db $AF
	
; Data from 1306 to 1306 (1 bytes)	
	.db $F5
	
; Data from 1307 to 1307 (1 bytes)	
	.db $33
	
; Data from 1308 to 130A (3 bytes)	
	.db $CD $7D $0F
	
; Data from 130B to 130B (1 bytes)	
	.db $33
	
; Data from 130C to 130E (3 bytes)	
	.db $CD $D8 $10
	
; Data from 130F to 130F (1 bytes)	
	.db $7D
	
; Data from 1310 to 1310 (1 bytes)	
A$title_screen$164:	
	.db $B7
	
; Data from 1311 to 1312 (2 bytes)	
A$title_screen$165:	
	.db $28 $03
	
; Data from 1313 to 1315 (3 bytes)	
A$title_screen$169:	
C$title_screen.c$45$2$29:	
	.db $CD $07 $11
	
; Data from 1316 to 1318 (3 bytes)	
A$title_screen$174:	
C$title_screen.c$48$1$28:	
	.db $21 $2A $C0
	
; Data from 1319 to 1319 (1 bytes)	
A$title_screen$175:	
	.db $46
	
; Data from 131A to 131A (1 bytes)	
A$title_screen$176:	
	.db $C5
	
; Data from 131B to 131B (1 bytes)	
A$title_screen$177:	
	.db $33
	
; Data from 131C to 131E (3 bytes)	
A$title_screen$178:	
	.db $CD $7D $0F
	
; Data from 131F to 131F (1 bytes)	
A$title_screen$179:	
	.db $33
	
; Data from 1320 to 1322 (3 bytes)	
A$title_screen$183:	
C$title_screen.c$49$1$28:	
	.db $21 $2A $C0
	
; Data from 1323 to 1323 (1 bytes)	
A$title_screen$184:	
	.db $46
	
; Data from 1324 to 1324 (1 bytes)	
A$title_screen$185:	
	.db $C5
	
; Data from 1325 to 1325 (1 bytes)	
A$title_screen$186:	
	.db $33
	
; Data from 1326 to 1328 (3 bytes)	
A$title_screen$187:	
	.db $CD $67 $0B
	
; Data from 1329 to 1329 (1 bytes)	
A$title_screen$188:	
	.db $33
	
; Data from 132A to 132C (3 bytes)	
A$title_screen$192:	
C$title_screen.c$51$1$28:	
	.db $21 $60 $C0
	
; Data from 132D to 132E (2 bytes)	
A$title_screen$193:	
	.db $36 $00
	
; Data from 132F to 1331 (3 bytes)	
A$title_screen$197:	
C$title_screen.c$52$1$28:	
	.db $21 $61 $C0
	
; Data from 1332 to 1333 (2 bytes)	
A$title_screen$198:	
	.db $36 $00
	
; Data from 1334 to 1334 (1 bytes)	
A$title_screen$203:	
C$title_screen.c$53$1$28:	
XG$screen_title_screen_load$0$0:	
	ret
	
; Data from 1335 to 1340 (12 bytes)	
Ftitle_screen$__str_0$0$0:	
	.db $50 $52 $45 $53 $53 $20 $53 $54 $41 $52 $54 $00
	
; Data from 1341 to 1347 (7 bytes)	
Ftitle_screen$__str_1$0$0:	
	.db $52 $45 $43 $4F $52 $44 $00
	
; Data from 1348 to 134E (7 bytes)	
Ftitle_screen$__str_2$0$0:	
	.db $43 $4F $56 $45 $52 $53 $00
	
; Data from 134F to 1353 (5 bytes)	
Ftitle_screen$__str_3$0$0:	
	.db $56 $31 $2E $30 $00
	
; Data from 1354 to 1355 (2 bytes)	
A$title_screen$229:	
C$title_screen.c$55$1$28:	
G$screen_title_screen_update$0$0:	
_screen_title_screen_update:	
	.db $DD $E5
	
; Data from 1356 to 1359 (4 bytes)	
A$title_screen$230:	
	.db $DD $21 $00 $00
	
; Data from 135A to 135B (2 bytes)	
A$title_screen$231:	
	.db $DD $39
	
; Data from 135C to 135C (1 bytes)	
A$title_screen$232:	
	.db $F5
	
; Data from 135D to 135D (1 bytes)	
A$title_screen$233:	
	.db $3B
	
; Data from 135E to 1360 (3 bytes)	
A$title_screen$237:	
C$title_screen.c$69$1$31:	
	.db $DD $7E $04
	
; Data from 1361 to 1363 (3 bytes)	
A$title_screen$238:	
	.db $DD $77 $FE
	
; Data from 1364 to 1366 (3 bytes)	
A$title_screen$239:	
	.db $DD $7E $05
	
; Data from 1367 to 1369 (3 bytes)	
A$title_screen$240:	
	.db $DD $77 $FF
	
; Data from 136A to 136C (3 bytes)	
A$title_screen$244:	
C$title_screen.c$60$1$31:	
	.db $3A $60 $C0
	
; Data from 136D to 136D (1 bytes)	
A$title_screen$245:	
	.db $3D
	
; Data from 136E to 136F (2 bytes)	
A$title_screen$246:	
	.db $20 $36
	
; Data from 1370 to 1372 (3 bytes)	
A$title_screen$250:	
C$title_screen.c$62$2$32:	
	.db $CD $B3 $11
	
; Data from 1373 to 1373 (1 bytes)	
A$title_screen$251:	
	.db $4D
	
; Data from 1374 to 1374 (1 bytes)	
A$title_screen$255:	
C$title_screen.c$63$2$32:	
	.db $79
	
; Data from 1375 to 1375 (1 bytes)	
A$title_screen$256:	
	.db $B7
	
; Data from 1376 to 1377 (2 bytes)	
A$title_screen$257:	
	.db $28 $1B
	
; Data from 1378 to 1378 (1 bytes)	
A$title_screen$261:	
C$title_screen.c$65$3$33:	
	.db $C5
	
; Data from 1379 to 137B (3 bytes)	
A$title_screen$262:	
	.db $21 $0A $15
	
; Data from 137C to 137C (1 bytes)	
A$title_screen$263:	
	.db $E5
	
; Data from 137D to 137F (3 bytes)	
A$title_screen$264:	
	.db $21 $07 $14
	
; Data from 1380 to 1380 (1 bytes)	
A$title_screen$265:	
	.db $E5
	
; Data from 1381 to 1383 (3 bytes)	
A$title_screen$266:	
	.db $CD $E9 $0D
	
; Data from 1384 to 1384 (1 bytes)	
A$title_screen$267:	
	.db $F1
	
; Data from 1385 to 1387 (3 bytes)	
A$title_screen$268:	
	.db $21 $15 $17
	
; Data from 1388 to 1388 (1 bytes)	
A$title_screen$269:	
	.db $E3
	
; Data from 1389 to 138B (3 bytes)	
A$title_screen$270:	
	.db $21 $07 $14
	
; Data from 138C to 138C (1 bytes)	
A$title_screen$271:	
	.db $E5
	
; Data from 138D to 138F (3 bytes)	
A$title_screen$272:	
	.db $CD $E9 $0D
	
; Data from 1390 to 1390 (1 bytes)	
A$title_screen$273:	
	.db $F1
	
; Data from 1391 to 1391 (1 bytes)	
A$title_screen$274:	
	.db $F1
	
; Data from 1392 to 1392 (1 bytes)	
A$title_screen$275:	
	.db $C1
	
; Data from 1393 to 1393 (1 bytes)	
A$title_screen$280:	
C$title_screen.c$69$2$32:	
	.db $79
	
; Data from 1394 to 1394 (1 bytes)	
A$title_screen$281:	
	.db $B7
	
; Data from 1395 to 1396 (2 bytes)	
A$title_screen$282:	
	.db $28 $04
	
; Data from 1397 to 1398 (2 bytes)	
A$title_screen$283:	
	.db $0E $03
	
; Data from 1399 to 139A (2 bytes)	
A$title_screen$284:	
	.db $18 $02
	
; Data from 139B to 139C (2 bytes)	
A$title_screen$286:	
	.db $0E $02
	
; Data from 139D to 139F (3 bytes)	
A$title_screen$288:	
	.db $DD $6E $FE
	
; Data from 13A0 to 13A2 (3 bytes)	
A$title_screen$289:	
	.db $DD $66 $FF
	
; Data from 13A3 to 13A3 (1 bytes)	
A$title_screen$290:	
	.db $71
	
; Data from 13A4 to 13A5 (2 bytes)	
A$title_screen$294:	
C$title_screen.c$70$2$32:	
	.db $18 $5C
	
; Data from 13A6 to 13A8 (3 bytes)	
A$title_screen$299:	
C$title_screen.c$73$1$31:	
	.db $CD $7C $11
	
; Data from 13A9 to 13AB (3 bytes)	
A$title_screen$303:	
C$title_screen.c$74$1$31:	
	.db $DD $75 $FD
	
; Data from 13AC to 13AC (1 bytes)	
A$title_screen$304:	
	.db $7D
	
; Data from 13AD to 13AD (1 bytes)	
A$title_screen$305:	
	.db $B7
	
; Data from 13AE to 13AF (2 bytes)	
A$title_screen$306:	
	.db $28 $29
	
; Data from 13B0 to 13B2 (3 bytes)	
A$title_screen$310:	
C$title_screen.c$76$2$34:	
	.db $21 $61 $C0
	
; Data from 13B3 to 13B4 (2 bytes)	
A$title_screen$311:	
	.db $3E $01
	
; Data from 13B5 to 13B5 (1 bytes)	
A$title_screen$312:	
	.db $96
	
; Data from 13B6 to 13B6 (1 bytes)	
A$title_screen$313:	
	.db $77
	
; Data from 13B7 to 13B9 (3 bytes)	
A$title_screen$317:	
C$title_screen.c$77$2$34:	
	.db $3A $61 $C0
	
; Data from 13BA to 13BA (1 bytes)	
A$title_screen$318:	
	.db $B7
	
; Data from 13BB to 13BC (2 bytes)	
A$title_screen$319:	
	.db $28 $0F
	
; Data from 13BD to 13BF (3 bytes)	
A$title_screen$323:	
C$title_screen.c$79$3$35:	
	.db $21 $0A $15
	
; Data from 13C0 to 13C0 (1 bytes)	
A$title_screen$324:	
	.db $E5
	
; Data from 13C1 to 13C3 (3 bytes)	
A$title_screen$325:	
	.db $21 $07 $14
	
; Data from 13C4 to 13C4 (1 bytes)	
A$title_screen$326:	
	.db $E5
	
; Data from 13C5 to 13C7 (3 bytes)	
A$title_screen$327:	
	.db $CD $E9 $0D
	
; Data from 13C8 to 13C8 (1 bytes)	
A$title_screen$328:	
	.db $F1
	
; Data from 13C9 to 13C9 (1 bytes)	
A$title_screen$329:	
	.db $F1
	
; Data from 13CA to 13CB (2 bytes)	
A$title_screen$330:	
	.db $18 $0D
	
; Data from 13CC to 13CE (3 bytes)	
A$title_screen$335:	
C$title_screen.c$83$3$36:	
	.db $21 $0A $15
	
; Data from 13CF to 13CF (1 bytes)	
A$title_screen$336:	
	.db $E5
	
; Data from 13D0 to 13D2 (3 bytes)	
A$title_screen$337:	
	.db $21 $13 $14
	
; Data from 13D3 to 13D3 (1 bytes)	
A$title_screen$338:	
	.db $E5
	
; Data from 13D4 to 13D6 (3 bytes)	
A$title_screen$339:	
	.db $CD $E9 $0D
	
; Data from 13D7 to 13D7 (1 bytes)	
A$title_screen$340:	
	.db $F1
	
; Data from 13D8 to 13D8 (1 bytes)	
A$title_screen$341:	
	.db $F1
	
; Data from 13D9 to 13DA (2 bytes)	
A$title_screen$346:	
C$title_screen.c$87$1$31:	
	.db $3E $10
	
; Data from 13DB to 13DB (1 bytes)	
A$title_screen$347:	
	.db $F5
	
; Data from 13DC to 13DC (1 bytes)	
A$title_screen$348:	
	.db $33
	
; Data from 13DD to 13DF (3 bytes)	
A$title_screen$349:	
	.db $CD $D3 $0E
	
; Data from 13E0 to 13E0 (1 bytes)	
A$title_screen$350:	
	.db $33
	
; Data from 13E1 to 13E1 (1 bytes)	
A$title_screen$354:	
C$title_screen.c$88$1$31:	
	.db $7D
	
; Data from 13E2 to 13E2 (1 bytes)	
A$title_screen$355:	
	.db $B7
	
; Data from 13E3 to 13E4 (2 bytes)	
A$title_screen$356:	
	.db $28 $15
	
; Data from 13E5 to 13E7 (3 bytes)	
A$title_screen$360:	
C$title_screen.c$90$2$37:	
	.db $21 $0A $15
	
; Data from 13E8 to 13E8 (1 bytes)	
A$title_screen$361:	
	.db $E5
	
; Data from 13E9 to 13EB (3 bytes)	
A$title_screen$362:	
	.db $21 $13 $14
	
; Data from 13EC to 13EC (1 bytes)	
A$title_screen$363:	
	.db $E5
	
; Data from 13ED to 13EF (3 bytes)	
A$title_screen$364:	
	.db $CD $E9 $0D
	
; Data from 13F0 to 13F0 (1 bytes)	
A$title_screen$365:	
	.db $F1
	
; Data from 13F1 to 13F1 (1 bytes)	
A$title_screen$366:	
	.db $F1
	
; Data from 13F2 to 13F4 (3 bytes)	
A$title_screen$370:	
C$title_screen.c$91$2$37:	
	.db $CD $70 $0A
	
; Data from 13F5 to 13F7 (3 bytes)	
A$title_screen$374:	
C$title_screen.c$93$2$37:	
	.db $21 $60 $C0
	
; Data from 13F8 to 13F9 (2 bytes)	
A$title_screen$375:	
	.db $36 $01
	
; Data from 13FA to 13FC (3 bytes)	
A$title_screen$380:	
C$title_screen.c$96$1$31:	
	.db $DD $6E $FE
	
; Data from 13FD to 13FF (3 bytes)	
A$title_screen$381:	
	.db $DD $66 $FF
	
; Data from 1400 to 1401 (2 bytes)	
A$title_screen$382:	
	.db $36 $02
	
; Data from 1402 to 1403 (2 bytes)	
A$title_screen$384:	
	.db $DD $F9
	
; Data from 1404 to 1405 (2 bytes)	
A$title_screen$385:	
	.db $DD $E1
	
; Data from 1406 to 1406 (1 bytes)	
A$title_screen$390:	
C$title_screen.c$97$1$31:	
XG$screen_title_screen_update$0$:	
	ret
	
; Data from 1407 to 1412 (12 bytes)	
Ftitle_screen$__str_4$0$0:	
	.dsb 11, $20
	.db $00
	
; Data from 1413 to 141E (12 bytes)	
Ftitle_screen$__str_5$0$0:	
	.db $50 $52 $45 $53 $53 $20 $53 $54 $41 $52 $54 $00